version: "2.4"
services:
  rpmrepo:
    build:
      context: ./createrepo
    container_name: rpmrepo
    hostname: rpmrepo
    restart: unless-stopped
    volumes:
      - "/opt/rpm/gpg:/root/.gnupg"
      - "/var/www/packages:/data/centos/packages"
    env_file:
      - rpmrepo.env
    ports:
      - "80:80"
