version: "2.4"
services:
  rpmrepo:
    build:
      context: ./createrepo
    container_name: rpmrepo
    hostname: rpmrepo
    restart: unless-stopped
    volumes:
      - "/opt/rpm/gpg:/root/.gnupg"
      - "/var/www/packages:/data/centos/packages"
    environment:
      - GPG_NAME="Dude"
      - GPG_COMMENT="Key for signing rpm packages"
      - GPG_EMAIL=dude@example.com
      - GPG_EXPIRE=0
      - GPG_PASS=ChangeMePlease
    ports:
      - "6667:80"
