version: "2.4"
services:
  cvetool-web:
    image: airship.svc.mirantis.net:6669/cvetool-web:latest
    container_name: cvetool-web
    hostname: cvetool-web
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/cvetool-web/nvd.db:/etc/cvetool/nvd.db"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - "/opt/cvetool-web/ssl/:/etc/ssl/"
    environment:
      - NGINX_PROXY_URL=http://cvetool-web:5000/
      - NGINX_DOMAIN_NAME=example.domain.com
    ports:
      - "443:443"
      - "80:80"
