version: "2.4"
services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: unless-stopped
    volumes:
      - "/opt/registry/auth:/auth"
      - "/opt/registry/certs:/certs"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    ports:
      - "443:443"
