version: "2.4"
services:
  aptly:
    build: ./docker-aptly/ 
    image: aptly:latest
    container_name: aptly
    hostname: aptly
    restart: unless-stopped
    volumes:
      - "/opt/apt/gpg:/root/.gnupg"
      - "/opt/apt/aptly:/opt/aptly"
      - "/opt/apt/packages:/opt/packages"
    environment:
      - FULL_NAME="APT Repository"
      - EMAIL_ADDRESS=dude@example.com
      - GPG_PASSWORD=ChangeMePlease
      - HOSTNAME=apt.example.com
    ports:
      - "6666:80"
