version: "2.4"
services:
  aptly:
    image: bryanhong/aptly:latest
    container_name: aptly
    hostname: aptly
    restart: unless-stopped
    volumes:
      - "/opt/apt/gpg:/root/.gnupg"
      - "/opt/apt/aptly:/opt/aptly"
      - "/opt/apt/packages:/opt/packages"
    environment:
      - FULL_NAME="APT Repository"
      - EMAIL_ADDRESS=dude@example.com
      - GPG_PASSWORD=ChangeMePlease
      - HOSTNAME=apt.example.com
    ports:
      - "6666:80"

# Make files available for downloading with wget
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    volumes:
    - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    - "/opt/apt/packages/:/var/www/packages"
    ports:
    - "6668:80"
